#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=16384
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=00:00:30
#SBATCH --output=/home/michels/results/taylor/s%x.out

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/taylor/bin/activate

shopt -s extglob

echo STARTING AT `date`
pwd

xpdir="/home/michels/results/taylor/${SLURM_JOB_NAME}"

mkdir -p ${xpdir}
mkdir -p ${xpdir}/logs

# Dataset
dataset='jaad'
jaadsubset='default'
trainsplit='train'
evalsplit='val'

# Training
lr=0.0005
epochs=5

# Model
mtlgradmerge='power'

attributes='all'
duplicates=36
taskweight=7.0
lambdas="${taskweight} ${taskweight} ${taskweight} ${taskweight} 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0"

sthreshold=0.2
minclustersize=10
epsilon=5.0
clusterthreshold=0.5

# cd /home/michels/detection-attributes-fields/
cd /home/michels/luc_detect/


mkdir -p ${xpdir}/predictions
for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_${evalepoch} \
    --dataset ${dataset} \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --fork-normalization-operation ${mtlgradmerge} \
    --fork-normalization-duplicates ${duplicates} \
    --head-consolidation 'filter_and_extend' \
    --decoder-s-threshold ${sthreshold} \
    --decoder-optics-min-cluster-size ${minclustersize} \
    --decoder-optics-epsilon ${epsilon} \
    --decoder-optics-cluster-threshold ${clusterthreshold} \
    --jaad-slice 0 30 \
    2>&1 | tee ${xpdir}/logs/eval_${evalepoch}_log.txt
  echo "Evaluation done!"
done

cd -

echo FINISHED at `date`

deactivate