#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=16384
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=02:00:00 # 2:45
#SBATCH --output=/home/michels/results/taylor/s%x.out

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/taylor/bin/activate

shopt -s extglob

echo STARTING AT `date`
pwd

xpdir="/home/michels/results/taylor/${SLURM_JOB_NAME}"

mkdir -p ${xpdir}
mkdir -p ${xpdir}/logs

# Dataset
dataset='jaad-cocokp'
jaadsubset='default'
trainsplit='hazik_train'
evalsplit='hazik_test'
# COCO
COCO_ANNOTATIONS_TRAIN='/work/vita/data-coco/annotations/person_keypoints_train2017.json'
COCO_ANNOTATIONS_VAL='/work/vita/data-coco/annotations/person_keypoints_val2017.json'
COCO_IMAGE_DIR_TRAIN='/work/vita/data-coco/images/train2017/'
COCO_IMAGE_DIR_VAL='/work/vita/data-coco/images/val2017/'
# Training
lr=1e-5
epochs=251
validation_epoch=251
attributes='hazik'
duplicates=2
lambdas="15.0 15.0 1.0 1.0"

SECONDS=0

checkpoint=resnet50

cd /home/michels/detection-attributes-fields/

mkdir -p ${xpdir}/predictions
mkdir -p ${xpdir}/images
echo "Start training..."
mkdir -p ${xpdir}/checkpoints

srun time python3 -m openpifpaf.train \
  --output ${xpdir}/checkpoints/model.pt \
  --dataset ${dataset} \
  --jaad-root-dir /work/vita/datasets/JAAD/ \
  --jaad-subset ${jaadsubset} \
  --jaad-training-set ${trainsplit} \
  --jaad-validation-set ${evalsplit} \
  --cocokp-train-annotations ${COCO_ANNOTATIONS_TRAIN} \
  --cocokp-val-annotations ${COCO_ANNOTATIONS_VAL} \
  --cocokp-train-image-dir ${COCO_IMAGE_DIR_TRAIN} \
  --cocokp-val-image-dir ${COCO_IMAGE_DIR_VAL} \
  --cocokp-orientation-invariant 0.1 \
  --cocokp-upsample=2 \
  --coco-eval-orientation-invariant 0.0 \
  --ema 1e-3 \
  --auto-tune-mtl \
  --log-interval 10 \
  --val-interval 1 \
  --val-batches 1 \
  --epochs ${epochs} \
  --batch-size 4 \
  --lr ${lr} \
  --weight-decay 0 \
  --momentum 0.95 \
  --checkpoint ${checkpoint} \
  --attribute-regression-loss l2 \
  --jaad-head-upsample 2 \
  --jaad-pedestrian-attributes ${attributes} \
  --lambdas ${lambdas} \
  --jaad-invert 99999 \
  2>&1 | tee ${xpdir}/logs/train_log.txt
echo "Training done!"





cd -

echo FINISHED at `date` 

echo $SECONDS # 5280

deactivate