#!/bin/bash -l

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --mem=16384
#SBATCH --partition=gpu
#SBATCH --qos=gpu
#SBATCH --gres=gpu:1
#SBATCH --time=00:00:30
#SBATCH --output=/home/michels/results/taylor/s%x.out

module purge
module load gcc/8.4.0-cuda python/3.7.7
source /home/michels/venvs/taylor/bin/activate

shopt -s extglob

echo STARTING AT `date`
pwd

xpdir="/home/michels/results/taylor/${SLURM_JOB_NAME}"

mkdir -p ${xpdir}
mkdir -p ${xpdir}/logs

# Dataset
dataset='jaad-cocokp'
jaadsubset='default'
trainsplit='trainval'
evalsplit='test'

# Training
lr=0.0005
epochs=251

# COCO
COCO_ANNOTATIONS_TRAIN='/work/vita/data-coco/annotations/person_keypoints_train2017.json'
COCO_ANNOTATIONS_VAL='/work/vita/data-coco/annotations/person_keypoints_val2017.json'
COCO_IMAGE_DIR_TRAIN='/work/vita/data-coco/images/train2017/'
COCO_IMAGE_DIR_VAL='/work/vita/data-coco/images/val2017/'

# Model
mtlgradmerge='power'

attributes='detection will_cross'
duplicates=35
taskweight=7.0
lambdas="${taskweight} ${taskweight} ${taskweight} ${taskweight} 1.0 0.00001 0.00001"

sthreshold=0.2
minclustersize=10
epsilon=5.0
clusterthreshold=0.5

cd /home/michels/luc_detect/
SECONDS=0


echo "Start training..."
mkdir -p ${xpdir}/checkpoints

srun time python3 -m openpifpaf.train \
  --output ${xpdir}/checkpoints/model.pt \
  --dataset ${dataset} \
  --jaad-root-dir /work/vita/datasets/JAAD/ \
  --jaad-subset ${jaadsubset} \
  --jaad-training-set ${trainsplit} \
  --jaad-validation-set ${evalsplit} \
  --cocokp-train-annotations ${COCO_ANNOTATIONS_TRAIN} \
  --cocokp-val-annotations ${COCO_ANNOTATIONS_VAL} \
  --cocokp-train-image-dir ${COCO_IMAGE_DIR_TRAIN} \
  --cocokp-val-image-dir ${COCO_IMAGE_DIR_VAL} \
  --cocokp-orientation-invariant 0.1 \
  --cocokp-upsample=2 \
  --coco-eval-orientation-invariant 0.0 \
  --log-interval 11 \
  --val-interval 1 \
  --val-batches 1 \
  --epochs ${epochs} \
  --batch-size 4 \
  --lr ${lr} \
  --weight-decay 5e-4 \
  --momentum 0.95 \
  --checkpoint resnet50 \
  --jaad-pedestrian-attributes ${attributes} \
  --detection-bias-prior 0.01 \
  --jaad-head-upsample 2 \
  --lambdas ${lambdas} \
  --attribute-regression-loss l1 \
  --attribute-focal-gamma 2 \
  --auto-tune-mtl \
  2>&1 | tee ${xpdir}/logs/train_log.txt
echo "Training done!"

mkdir -p ${xpdir}/predictions
mkdir -p ${xpdir}/images

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset ${dataset} \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --head-consolidation 'filter_and_extend' \
    --decoder-s-threshold ${sthreshold} \
    --decoder-optics-min-cluster-size ${minclustersize} \
    --decoder-optics-epsilon ${epsilon} \
    --decoder-optics-cluster-threshold ${clusterthreshold} \
    --jaad-metrics "instance" \
    --jaad-slice 0 30 \
    2>&1 | tee ${xpdir}/logs/eval_1_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset ${dataset} \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --head-consolidation 'filter_and_extend' \
    --decoder-s-threshold ${sthreshold} \
    --decoder-optics-min-cluster-size ${minclustersize} \
    --decoder-optics-epsilon ${epsilon} \
    --decoder-optics-cluster-threshold ${clusterthreshold} \
    --jaad-metrics "instance" \
    --jaad-slice 0 60 \
    2>&1 | tee ${xpdir}/logs/eval_2_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset ${dataset} \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --head-consolidation 'filter_and_extend' \
    --decoder-s-threshold ${sthreshold} \
    --decoder-optics-min-cluster-size ${minclustersize} \
    --decoder-optics-epsilon ${epsilon} \
    --decoder-optics-cluster-threshold ${clusterthreshold} \
    --jaad-metrics "instance" \
    --jaad-slice 0 90 \
    2>&1 | tee ${xpdir}/logs/eval_3_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset ${dataset} \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --head-consolidation 'filter_and_extend' \
    --decoder-s-threshold ${sthreshold} \
    --decoder-optics-min-cluster-size ${minclustersize} \
    --decoder-optics-epsilon ${epsilon} \
    --decoder-optics-cluster-threshold ${clusterthreshold} \
    --jaad-metrics "instance" \
    --jaad-slice 0 120 \
    2>&1 | tee ${xpdir}/logs/eval_4_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset jaad \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --head-consolidation=keep \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --force-complete-pose --seed-threshold=0.2 \
    --decoder-use-pifpaf-bbox \
    --jaad-metrics "hazik_instance" \
    --jaad-invert 99999 \
    --jaad-slice 0 30 \
    2>&1 | tee ${xpdir}/logs/eval_1_h_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset jaad \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --head-consolidation=keep \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --force-complete-pose --seed-threshold=0.2 \
    --decoder-use-pifpaf-bbox \
    --jaad-metrics "hazik_instance" \
    --jaad-invert 99999 \
    --jaad-slice 0 60 \
    2>&1 | tee ${xpdir}/logs/eval_2_h_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset jaad \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --head-consolidation=keep \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --force-complete-pose --seed-threshold=0.2 \
    --decoder-use-pifpaf-bbox \
    --jaad-metrics "hazik_instance" \
    --jaad-invert 99999 \
    --jaad-slice 0 90 \
    2>&1 | tee ${xpdir}/logs/eval_3_h_${evalepoch}_log.txt
  echo "Evaluation done!"
done

for evalfrom in $(ls -1v ${xpdir}/checkpoints/*.pt.epoch+([0-9]))
do
  echo "Start evaluating ${evalfrom}..."
  evalepoch=${evalfrom: -3}
  srun time python3 -m openpifpaf.eval \
    --output ${xpdir}/predictions/model_slice_1_${evalepoch} \
    --dataset jaad \
    --jaad-root-dir /work/vita/datasets/JAAD/ \
    --jaad-subset ${jaadsubset} \
    --jaad-testing-set ${evalsplit} \
    --checkpoint ${evalfrom} \
    --batch-size 4 \
    --head-consolidation=keep \
    --jaad-head-upsample 2 \
    --jaad-pedestrian-attributes ${attributes} \
    --force-complete-pose --seed-threshold=0.2 \
    --decoder-use-pifpaf-bbox \
    --jaad-metrics "hazik_instance" \
    --jaad-invert 99999 \
    --jaad-slice 0 120 \
    2>&1 | tee ${xpdir}/logs/eval_4_h_${evalepoch}_log.txt
  echo "Evaluation done!"
done

cd -

echo FINISHED at `date`

deactivate
echo $SECONDS